version: "3"
services:
  sql-service:
    build: ./sql-service/
    container_name: sql-service
    ports: 
      - "3306:3306"
    volumes:
      - ./volumes/sql-service:/var/lib/mysql
  auth-service:
    build: ./authentication-service/
    container_name: auth-service
    ports: 
      - "8082:8082"
  video-storage-service:
    build: ./video-storage-service/
    container_name: video-storage-service
    ports:
      - "8084:8084"
    volumes: 
      - ./volumes/video-storage-service:/tmp
  upload-service:
    build: ./upload-service/
    container_name: upload-service
    ports:
      - "8081:8080"
    depends_on:
      - sql-service
      - auth-service
      - video-storage-service
  stream-service:
    build: ./stream-service/
    container_name: stream-service
    ports:
      - "8085:8085"
    depends_on:
      - sql-service
      - auth-service
      - video-storage-service
    
